tons of updates

diff --git a/template.yaml b/template.yaml
--- a/template.yaml
+++ b/template.yaml
@@ -1,29 +1,36 @@
 Transform: AWS::LanguageExtensions
-Description: VPC for On-AWS deployment.
+Description: |
+  DISCLAIMER: This CloudFormation template is provided as-is without any warranties, express or implied.
+  The user assumes all responsibility for the deployment, operation, and management of resources created
+  using this template. The user is responsible for understanding the configuration, security implications,
+  and costs associated with the resources. The creator of this template is not liable for any damages,
+  data loss, or costs incurred through the use of this template. It is recommended to review this template
+  thoroughly and test in a non-production environment before deploying to production.
+
+Parameters:
+  ImageId:
+    Description: AL2023
+    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
+    Default: /aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64
 
 Mappings:
   Configuration:
-    us-east-1:
-      Ami: ami-024cf76afbc833688
-    us-west-2:
-      Ami: ami-0218a6903ac31c61f
-    ca-central-1:
-      Ami: ami-0c863e000bf13d94b
-    eu-west-1:
-      Ami: ami-0137cee1a6fb4f763
     Spot:
       MaxPrice: 0.003
     VPC:
-      CidrBlock: 10.192.0.0/18
+      CidrBlock: 10.192.0.0/17
     PublicSubnet:
-      A: 10.192.0.0/20
-      B: 10.192.16.0/20
+      A: 10.192.0.0/20    #10.192.128.0/20
+      B: 10.192.16.0/20   #10.192.144.0/20
+      C: 10.192.32.0/20   #10.192.160.0/20
     PrivateSubnet:
-      A: 10.192.32.0/20
-      B: 10.192.48.0/20
+      A: 10.192.48.0/20   #10.192.176.0/20
+      B: 10.192.64.0/20   #10.192.192.0/20
+      C: 10.192.80.0/20   #10.192.208.0/20
     AZ:
       A: 0
       B: 1
+      C: 2
     Logs:
       RetentionInDays: 30
 
@@ -103,7 +110,7 @@ Resources:
 
   Fn::ForEach::Subnet:
     - Letter
-    - [ A, B ]
+    - [ A, B, C ]
     - PublicSubnet${Letter}:
         Type: AWS::EC2::Subnet
         Properties:
@@ -168,6 +175,18 @@ Resources:
           CidrIp: 0.0.0.0/0
       SecurityGroupIngress:
         - IpProtocol: tcp
+          FromPort: 80
+          ToPort: 80
+          CidrIp: !FindInMap [ Configuration, PrivateSubnet, A ]
+        - IpProtocol: tcp
+          FromPort: 80
+          ToPort: 80
+          CidrIp: !FindInMap [ Configuration, PrivateSubnet, B ]
+        - IpProtocol: tcp
+          FromPort: 80
+          ToPort: 80
+          CidrIp: !FindInMap [ Configuration, PrivateSubnet, C ]
+        - IpProtocol: tcp
           FromPort: 443
           ToPort: 443
           CidrIp: !FindInMap [ Configuration, PrivateSubnet, A ]
@@ -175,6 +194,10 @@ Resources:
           FromPort: 443
           ToPort: 443
           CidrIp: !FindInMap [ Configuration, PrivateSubnet, B ]
+        - IpProtocol: tcp
+          FromPort: 443
+          ToPort: 443
+          CidrIp: !FindInMap [ Configuration, PrivateSubnet, C ]
       Tags:
         - Key: Name
           Value: NAT
@@ -210,6 +233,7 @@ Resources:
                 Resource:
                   - !Sub arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:route-table/${PrivateRouteTableA}
                   - !Sub arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:route-table/${PrivateRouteTableB}
+                  - !Sub arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:route-table/${PrivateRouteTableC}
 
   InstanceProfile:
     Type: AWS::IAM::InstanceProfile
@@ -222,7 +246,7 @@ Resources:
     Type: AWS::EC2::LaunchTemplate
     Properties:
       LaunchTemplateData:
-        ImageId: !FindInMap [ Configuration, !Ref AWS::Region, Ami ]
+        ImageId: !Ref ImageId
         IamInstanceProfile:
           Arn: !GetAtt InstanceProfile.Arn
         NetworkInterfaces:
@@ -239,14 +263,35 @@ Resources:
           Fn::Base64:
             Fn::Sub: |
               #!/bin/bash
-              export instance=`curl http://169.254.169.254/latest/meta-data/instance-id`
-              export az=`curl http://169.254.169.254/latest/meta-data/placement/availability-zone`
+              yum update -y
+              yum install -y iptables-services
+              token=$(curl -X PUT "http://169.254.169.254/latest/api/token" \
+                     -H "X-aws-ec2-metadata-token-ttl-seconds: 21600" \
+                     --silent)
+              export instance=`curl -H "X-aws-ec2-metadata-token: $token" -s http://169.254.169.254/latest/meta-data/instance-id`
+              export az=`curl -H "X-aws-ec2-metadata-token: $token" -s http://169.254.169.254/latest/meta-data/placement/availability-zone`
               /opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource LaunchTemplate --region ${AWS::Region}
               /opt/aws/bin/cfn-signal '${UserDataHandle}'
     Metadata:
       AWS::CloudFormation::Init:
         config:
+          files:
+            /etc/sysctl.d/custom-ip-forwarding.conf:
+              content:
+                 net.ipv4.ip_forward=1
+              mode: 0644
+              owner: root
+              group: root
           commands:
+            00_iptables:
+              command: |
+                net=$(ip -o link show | sed -rn '/^[0-9]+: en/{s/.: ([^:]*):.*/\1/p}')
+                systemctl enable iptables
+                systemctl start iptables
+                sysctl -p /etc/sysctl.d/custom-ip-forwarding.conf
+                /sbin/iptables -t nat -A POSTROUTING -o $net -j MASQUERADE
+                /sbin/iptables -F FORWARD
+                service iptables save
             01_no_source_dest_check:
               command: !Sub |
                 aws ec2 modify-instance-attribute --region ${AWS::Region} \
@@ -300,10 +345,34 @@ Resources:
                     fi
                   fi
                 fi
+            04_replace_route_in_table_c:
+              command: !Sub |
+                if [[ $az == '${PrivateSubnetC.AvailabilityZone}' ]]
+                then
+                  aws ec2 create-route --region ${AWS::Region} \
+                    --route-table-id ${PrivateRouteTableC} \
+                    --instance-id $instance \
+                    --destination-cidr-block 0.0.0.0/0
+                  if [ $? -eq 0 ]
+                  then
+                    echo 'OK (route created)'
+                  else
+                    aws ec2 replace-route --region ${AWS::Region} \
+                      --route-table-id ${PrivateRouteTableC} \
+                      --instance-id $instance \
+                      --destination-cidr-block 0.0.0.0/0
+                    if [ $? -eq 0 ]
+                    then
+                      echo 'OK (route replaced)'
+                    else
+                      echo 'FAIL'
+                    fi
+                  fi
+                fi
 
   Fn::ForEach::Instance:
     - Letter
-    - [ A, B ]
+    - [ A, B, C ]
     - NatInstanceSpotFleet${Letter}:
         Type: AWS::EC2::EC2Fleet
         DependsOn: !Sub PrivateRouteTable${Letter}
@@ -350,12 +419,9 @@ Resources:
 Outputs:
   VPC:
     Value: !Ref VPC
-
   NatSecurityGroup:
     Value: !Ref NatSecurityGroup
-
   PublicSubnets:
-    Value: !Sub ${PublicSubnetA},${PublicSubnetB}
-
+    Value: !Sub ${PublicSubnetA},${PublicSubnetB},${PublicSubnetC}
   PrivateSubnets:
-    Value: !Sub ${PrivateSubnetA},${PrivateSubnetB}
+    Value: !Sub ${PrivateSubnetA},${PrivateSubnetB},${PrivateSubnetC}
